### ISSUE TITLE
[FEATURE] Search bar UX improvement

### ISSUE THREAD

**Issue by furkanmutlu** [furkanmutlu/fullstack-image-app#18]
After loading several more images, it is quite hard to scroll up again to search something else.

- It would be great to have search bar sticked to top when user scrolls down.
- It might look better to make its width 100% once its position is sticky.

**Comment by rabbanirizwan** [comment]
@furkanmutlu kindly assign me this

**Comment by furkanmutlu** [comment]
@rabbanirizwan Sure 👍

**Comment by rabbanirizwan** [comment]
https://github.com/furkanmutlu/fullstack-image-app/pull/21
kindly review @furkanmutlu
