### ISSUE TITLE
[FEATURE] Add go top button

### ISSUE THREAD

**Issue by furkanmutlu** [furkanmutlu/fullstack-image-app#28]
It would be nice to have Go top. button as image below.
- It should appear when search bar is wide.
- It would be nice to increase sticky features top distance.
- It should be aligned with Gallery below.
- We can also decrease the height of the search bar.

<img width="306" alt="image" src="https://user-images.githubusercontent.com/45897337/205733865-c9f55e61-535d-4261-a897-a7556f4bab4f.png">

**Comment by JJJ62** [comment]
I'll work on this feature

**Comment by furkanmutlu** [comment]
@JJJ62  any update on this?
