### ISSUE TITLE
[DOC] Nodejs version problem [FE]

### ISSUE THREAD

**Issue by enesbilici** [furkanmutlu/fullstack-image-app#29]
When starting frontend application, npm throws error. Frontend app supports  node version <= 16.x.x. Add this information to READ.me

**Comment by elyessAR** [comment]
You can download nvm to fix this.

**Comment by furkanmutlu** [comment]
@elyessAR @enesbilici Maybe we might consider updating the README ?

**Comment by elyessAR** [comment]
issue should be closed

**Comment by furkanmutlu** [comment]
@elyessAR  thanks for the update. Thats why it is nice to add `Closes #[NUMBER]` to your PR description. so when your PR merges it closes the mentioned issue automatically.
