### ISSUE TITLE
[FEATURE] Add expand button

### ISSUE THREAD

**Issue by furkanmutlu** [furkanmutlu/fullstack-image-app#38]
- Currently clicking of any image will expand the image.
- It would be nice to put this feature into an expand button like below.
- Button should be visible when user hovers over the image.
- Icon: `<FontAwesomeIcon icon="fa-solid fa-up-right-and-down-left-from-center" />`

![image](https://user-images.githubusercontent.com/45897337/208257297-6fd7ad7b-5bb3-46d3-967c-b32045696e0e.png)

Hover: 
![image](https://user-images.githubusercontent.com/45897337/208257997-89faa2f0-fdc0-4bfa-8d08-b73bd7f2af69.png)

**Comment by elyessAR** [comment]
I'll work on this

**Comment by elyessAR** [comment]
By the way, should we remove the cursor when user hover on image ?

**Comment by furkanmutlu** [comment]
> By the way, should we remove the cursor when user hover on image ?

Yes please, it wont be clickable anymore. Nice catch!
