### ISSUE TITLE
[FEATURE] Add like button

### ISSUE THREAD

**Issue by furkanmutlu** [furkanmutlu/fullstack-image-app#45]
- It would be nice ti have a like button like below:

- For this story please just create the UI, functionality of this button will be discussed on another ticket.
- Like button should be visible on hover state.
- Like button should be visible if image has like.
- User can like an image by hovering the image and clicking the like button
- User can like an image by double clicking AND double tapping.
- When user likes it, the heart icon should be filled.

Icons to use: 
- `<FontAwesomeIcon icon="fa-regular fa-heart" />`
- `<FontAwesomeIcon icon="fa-solid fa-heart" />`

<img width="227" alt="image" src="https://user-images.githubusercontent.com/45897337/209298413-b324bfdb-321a-49b7-b7c9-41a16808fa3c.png">

**Comment by 1san1** [comment]
Hey I would  like to contribute to this issue

**Comment by furkanmutlu** [comment]
Hi @1san1  seems like you removed your PR on this. I was planning work on your PR now. Please let me know if you are still interested maybe we can make it work together 💪 If not, I think I will start a new branch and assign to myself.

**Comment by 1san1** [comment]
hello @furkanmutlu  since you were unresponsive throughout the day yesterday I thought my code PR was not up to the expectation and just removed it sorry for that but I restored it if you are still interested.  By the way, it totally got off my mind that it was Christmas yesterday Merry Christmas.
