### ISSUE TITLE
[Bug] Filter/Remove duplicates

### ISSUE THREAD

**Issue by furkanmutlu** [furkanmutlu/fullstack-image-app#55]
Sometimes api return same id images. Liking one causes both liked.
Possible solution: Convert images to an array with unique image id 

![image](https://user-images.githubusercontent.com/45897337/209579981-2f75c372-ee65-41cf-849f-9acd11c87252.png)

**Comment by tarunsamanta2k20** [comment]
I would like to contribute to this issue. Please assign it to me.

**Comment by tarunsamanta2k20** [comment]
Although ids are same. But images are different. Right?

**Comment by furkanmutlu** [comment]
From what I see was images were the same too. Look at the screenshot 2nd and 3rd had same image and same id.

**Comment by tarunsamanta2k20** [comment]
@furkanmutlu check now from my latest commit

**Comment by furkanmutlu** [comment]
working on it.
