### ISSUE TITLE
[UX] Improve UX with Navbar  

### ISSUE THREAD

**Issue by furkanmutlu** [furkanmutlu/fullstack-image-app#56]
Currently when user is on 'PIXABAY' Gallery page and refreshes the page, app will display 'GIPHY' page as default. 
It would be nice to stay in the same page when user refreshes.

**Comment by navaneeth-dev** [comment]
I think a good way is to add a router. For example `/pixabay` goes to pixabay and `/` goes to giphy. Or if you don't want to add a router we could set a item in localStorage. What option do you want?

**Comment by furkanmutlu** [comment]
@navaneeth-dev that was my initial thought too. I think '/pixabay' goes pixabay, '/' and '/giphy' goes to giphy.
