### ISSUE TITLE
Add 'Add More' button OR pagination to fetch more images/gifs

### ISSUE THREAD

**Issue by furkanmutlu** [furkanmutlu/fullstack-image-app#6]
For now it is fetching 25 content from the api. It would be nice to have a button with plus icon in it at the very end of the page to fetch more content.  Or if you prefer pagination would work too.

**Comment by rd-code-23** [comment]
Im going to take up this issue instead of the other one as this one seems to be easier for me.
Should be done within a week.

**Comment by rd-code-23** [comment]
I created a pull request for this issue

**Comment by rd-code-23** [comment]
@furkanmutlu 
Hey, I haven't heard from you in a while, but I did push the changes: a820500afddc372e82257ec123d0a4c9b9acd858

**Comment by furkanmutlu** [comment]
@rd-code-23  Sorry for the late response, I was on holiday. I will take a look at it today or tomorrow. Thanks :)

**Comment by rd-code-23** [comment]
@furkanmutlu did you get a chance to look?
