### ISSUE TITLE
[FEATURE] Fix image size & alignment issue

### ISSUE THREAD

**Issue by furkanmutlu** [furkanmutlu/fullstack-image-app#9]
![image](https://user-images.githubusercontent.com/45897337/203855250-870a5fd2-f0ec-4023-81c3-8523c508af2f.png)

**Comment by Kd-Here** [comment]
Hey can I help you in that?

**Comment by furkanmutlu** [comment]
@Kd-Here yes you can. Do you want me to assign it to you ?

**Comment by furkanmutlu** [comment]
@Kd-Here  I have created a PR for #10 . There are few changes there might conflict with your work. I think I will wait for your PR, then merge mine. So that I can add you as a reviewer to #13

**Comment by Kd-Here** [comment]
Thanks @furkanmutlu for assigning that PR. Now I am trying to resolve the issue

**Comment by furkanmutlu** [comment]
@Kd-Here Did you create `.env` file in `backend` folder and add your `GIPHY_API_KEY` and `PIXABAY_API_KEY` ? 
Also did you run separately backend and frontend ? If you need help please let me know.

**Comment by Kd-Here** [comment]
Hello @furkanmutlu I run them in virtual env. Now it's showing only webpage without images.
I think I will not able to contribute since a beginner I don't know how to edit react webpages.

**Comment by furkanmutlu** [comment]
@Kd-Here no worries, I can try to help you to understand if you are interested.

**Comment by furkanmutlu** [comment]
Check this https://github.com/furkanmutlu/fullstack-image-app#:~:text=image%2Dapp.git-,Create,-.env%20file%20with

Seems like you didn't put your API key in 'backend/.env' file
